### ISSUE TITLE
Problem with the composer.json

### ISSUE THREAD

**Issue by hughsaffar** [nticaric/majestic-seo-api#1]
I tried to install this in my Laravel project by I do get a when I'm updating my composer.json. Here is the error:

Problem 1
    - Installation request for nticaric/majestic-seo-api dev-master -> satisfiable by nticaric/majestic-seo-api[dev-master].
    - nticaric/majestic-seo-api dev-master requires guzzlehttp/guzzle >=4,<6 -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

**Comment by nticaric** [comment]
I guess the problem was that the package wasn't available in a stable version but only in dev-master. 
Could you please try to change your `composer.json` to have `"nticaric/majestic-seo-api": "1.0.*"`

Hope this helps! Please let me know the outcome.

**Comment by hughsaffar** [comment]
It works! :+1: However still have the problem to integrate with a Laravel project.

**Comment by nticaric** [comment]
What seems to be the problem?

**Comment by hughsaffar** [comment]
Matter of fact it was a problem with the api! Now it is solved! Thanks :+1:

**Comment by nticaric** [comment]
Great!
